version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
      docker: 18
  pre_build:
    commands:
      - echo "Pre_build"
      - echo "Logging in to Amazon ECR"
      - $(aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 338102783115.dkr.ecr.us-east-1.amazonaws.com)
  build:
    commands:
      - echo "Build"
      - echo "Entered build phase"
      - echo "Building Java application"
      - cd Account-MS
      - mvn clean package
      - docker build -t ij032-pod5-account-microservices .
      - docker tag ij032-pod5-account-microservices:latest 338102783115.dkr.ecr.us-east-1.amazonaws.com/ij032-pod5-account-microservices:latest

  post_build:
    commands:
      - echo "Post_build"
      - docker push 338102783115.dkr.ecr.us-east-1.amazonaws.com/ij032-pod5-account-microservices:latest
      - printf '[{"name":"account-ms-container","imageUri":"%s"}]' docker push 338102783115.dkr.ecr.us-east-1.amazonaws.com/ij032-pod5-account-microservices:latest > taskdefinition.json
      - cat taskdefinition.json

artifacts:
  files:
      - Account-MS/taskdefinition.json
